[package]
name = "constellation"
version = "0.1.0"
authors = [
    "whs31 <ryazantsev.dl@edu.spbstu.ru>",
]
description = "Library for working with QuaSAR protocols and hardware"

[dependencies]
cmake = { version = "0.1.2", distribution = "sources" }
leaf = { version = "0.4.1", distribution = "static" }
leafconf = { version = "0.1.2", distribution = "static" }
